### ISSUE TITLE
AOT build error

### ISSUE THREAD

**Issue by ghost** [Promact/md2#143] opened 2017-03-29 07:05 UTC
Hello!

First of all, thanks for your wonderful components. 

After upgrading my Angular 2 app to Angular 4 I can no longer compile it using AOT because of this error:

```
ERROR in C:/full-path-here/src/$$_gendir/node_modules/md2/colorpicker/colorpicker.ngfactory.ts (1,1): Property 'isInputValidColor' is private and only accessible within class 'Md2Colorpicker'.
```

I guess it has to be made public instead of private? Could you please look into this so the app builds using AOT again.

**Comment by EndarValuk** [comment] 2017-03-31 06:00
Issue confirmed.
Used packages:
`    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "md2": "0.0.17",`

**Comment by dharmeshpipariya-zz** [comment] 2017-03-31 09:05
We have fixed the issue with release md2@0.0.18,
comment here if you have an issue

**Comment by n4uoase** [comment] 2017-04-02 11:41
Now as I updated to md2@0.0.18 when I run the compiler for aot i got following error:
`Error encountered resolving symbol values statically. Could not resolve @angular/animations relative to client-app/node_modules/md2/accordion/accordiontab.d.ts., resolving symbol Md2AccordionTab in client-app/node_modules/md2/accordion/accordiontab.d.ts, resolving symbol Md2AccordionTab in client-app/node_modules/md2/accordion/accordiontab.d.ts, resolving symbol Md2AccordionTab in client-app/node_modules/md2/accordion/accordiontab.d.ts`

**Comment by kgathuru** [comment] 2017-04-02 20:12
n4uoase, for your error 

> Could not resolve @angular/animations

Try `npm install @angular/animations --save`

@angular/animations is now a separate package in angular 4.0.0

**Closed as completed** 2017-04-03 04:18 UTC
Labels: bug

**Comment by n4uoase** [comment] 2017-04-03 13:01
@kgathuru 
Thanks, that helped me a lot.
I'm only wondering because I'm running in @angular/core 2.4.10 not 4.0.1?

Now after fixing this issue I ran into the next. Now a Problem in ng2-breadcrump, which is not part of md2.
